CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Formulario.urls', namespace='personas'))
]

CRUD/Formulario/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

app_name = 'persona'
urlpatterns = [
    # Vistas def
    # path('', views.lista_personas, name='lista_personas'),
    # path('editar/<int:cc>', views.editar_persona, name='editar_persona'),
    # path('eliminar/<int:cc>', views.eliminar_persona, name='eliminar_persona'),
    # path('nuevo', views.crear_persona, name='crear_persona'),

    # Vistas class
    # path('', LoginView.as_view(template_name='CRUD/Formulario/index.html'), name="login"),
    path('', views.ListaPersonas.as_view(), name='lista_personas'),
    path('personas/nuevo', views.CrearPersona.as_view(), name='crear_persona'),
    path('personas/editar/<pk>', views.EditarPersona.as_view(), name='editar_persona'),
    path('personas/eliminar/<pk>', views.EliminarPersona.as_view(), name='eliminar_persona'),

    path('mascotas', views.ListaMascotas.as_view(), name='lista_mascotas'),
    path('mascotas/nuevo', views.CrearMascota.as_view(), name='crear_mascota'),
    path('mascotas/editar/<pk>', views.EditarMascota.as_view(), name='editar_mascota'),
    path('mascotas/eliminar/<pk>', views.EliminarMascota.as_view(), name='eliminar_mascota'),

]

CRUD/Formulario/models.py
from django.db import models


class Persona(models.Model):
    HOMBRE = 'H'
    MUJER = 'M'

    GENEROS = (
        (HOMBRE, 'Hombre'),
        (MUJER, 'Mujer')
    )

    cc = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=150)
    telefono = models.IntegerField(blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    genero = models.CharField(max_length=2, choices=GENEROS)
    dob = models.DateField()
    bio = models.CharField(blank=True, null=True, default='', max_length=5000)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

    objetos = models.Manager()

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return str(self.nombre)


#    def get_absolute_url(self):
#        return reverse('formulario:persona_detail',
#                       args=[self.cc])

class Mascota(models.Model):

    especies =(
        ('Canino', 'Perro'),
        ('Felino', 'Gato'),
        ('Ave', 'Pajaro'),
        ('Pez', 'Pez'),
        ('Exotico','Exotico'),
        ('Otro','Otro')
    )

    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.SET_NULL)
    nombre = models.CharField(max_length=30)
    edad = models.IntegerField(blank=True, null=True)
    especie = models.CharField(max_length=6, choices=especies)
    color = models.CharField(max_length=25, blank=True, null=True)

CRUD/Formulario/forms.py
from django import forms
from .models import Persona, Mascota


class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['cc', 'nombre', 'telefono', 'email', 'genero', 'dob', 'bio']

        labels = {'cc': 'Documento de identidad',
                  'nombre': 'Nombre',
                  'telefono': 'Teléfono',
                  'email': 'Correo electrónico',
                  'genero': 'Genero',
                  'dob': 'Fecha de nacimiento',
                  'bio': 'Biografía',
                  }

        widgets = {
            'cc': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control', 'type': 'tel', 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'type': 'email', 'autocomplete': 'off'}),
            'genero': forms.Select(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'dob': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'autocomplete': 'off'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'autocomplete': 'off', 'placeholder': 'Dí algo sobre tí...'}),
        }


class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = [
            'persona', 'nombre', 'edad', 'especie', 'color'
        ]

        labels = {
            'persona': 'Dueño',
            'nombre': 'Nombre de la mascota',
            'edad': 'Edad',
            'especie': 'Especie',
            'color': 'Color'
        }

        widgets = {
            'persona': forms.Select(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'edad': forms.TextInput(attrs={'class': 'form-control', 'type': 'number',
                                           'autocomplete': 'off', 'min':'0', 'max': '100'}),
            'especie': forms.Select(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'color': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off', 'type': 'color'})
        }

CRUD/Formulario/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import PersonaForm, MascotaForm
from .models import Persona, Mascota


def lista_personas(request):
    personas = Persona.objetos.all()
    contexto = {'personas': personas}
    return render(request, 'CRUD/list.html', contexto)


def editar_persona(request, cc):
    persona = Persona.objetos.get(cc=cc)
    if request.method == 'GET':
        form = PersonaForm(instance=persona)
    else:
        form = PersonaForm(request.POST, instance=persona)
        if form.is_valid():
            form.save()
        return redirect('persona:lista_personas')
    return render(request, 'CRUD/form.html',
                  {'form': form})


def eliminar_persona(request, cc):
    persona = Persona.objetos.get(cc=cc)
    if request.method == 'POST':
        persona.delete()
        return redirect('persona:lista_personas')
    return render(request, 'CRUD/eliminar_persona.html',
                  {'persona': persona})


def crear_persona(request):
    if request.method == 'POST':
        form = PersonaForm(request.POST)
        if form.is_valid():
            nueva_persona = form.save(commit=False)
            nueva_persona.save()
        return redirect('persona:lista_personas')
    else:
        form = PersonaForm()
    return render(request, 'CRUD/form.html',
                  {'form': form})


class ListaPersonas(ListView):
    model = Persona
    template_name = 'CRUD/list.html'
    paginate_by = 10


class CrearPersona(CreateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'CRUD/form.html'
    success_url = reverse_lazy('persona:lista_personas')


class EditarPersona(UpdateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'CRUD/form.html'
    success_url = reverse_lazy('persona:lista_personas')


class EliminarPersona(DeleteView):
    model = Persona
    template_name = 'CRUD/eliminar_persona.html'
    success_url = reverse_lazy('persona:lista_personas')


class ListaMascotas(ListView):
    model = Mascota
    template_name = 'CRUD/list_mascotas.html'
    paginate_by = 10


class CrearMascota(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'CRUD/form_mascota.html'
    success_url = reverse_lazy('persona:lista_mascotas')


class EditarMascota(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'CRUD/form_mascota.html'
    success_url = reverse_lazy('persona:lista_mascotas')


class EliminarMascota(DeleteView):
    model = Mascota
    template_name = 'CRUD/eliminar_persona.html'
    success_url = reverse_lazy('persona:lista_mascotas')

# class CrearMascota(CreateView):
#     model = Mascota
#     template_name = 'CRUD/Formulario/form_mascota.html'
#     form_class = MascotaForm
#     second_form_class = PersonaForm
#     success_url = reverse_lazy('persona:lista_mascotas')
#
#     def get_context_data(self, **kwargs):
#         context = super(CrearMascota, self).get_context_data(**kwargs)
#         if 'form' not in context:
#             context['form'] = self.form_class(self.request.GET)
#         if 'form2' not in context:
#             context['form2'] = self.second_form_class(self.request.GET)
#         return context
#
#     def post(self, request, *args, **kwargs):
#         self.object = self.get_object
#         form = self.form_class(request.POST)
#         form2 = self.second_form_class(request.POST)
#         if form.is_valid() and form2.is_valid():
#             mascota = form.save()
#             mascota.persona = form2.save()
#             mascota.save()
#             return HttpResponseRedirect(self.get_success_url())
#         else:
#             return self.render_to_response(self.get_context_data(form=form, form2=form2))

CRUD/Formulario/templates/CRUD/eliminar_persona.html
{% extends "base.html" %}

{% block title %}Formulario{% endblock %}

{% block content %}

<div class="pt-4">
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
    <button type="submit" class="btn btn-outline-warning mt-3">Sí, eliminar</button>
    <a href="{% url 'persona:lista_personas' %}"><button type="button" class="btn btn-primary mt-3">Cancelar</button></a>
</form>
</div>

{% endblock %}

CRUD/Formulario/templates/CRUD/form.html
{% extends "base.html" %}

{% block title %}Formulario{% endblock %}

{% block content %}

<div class="pt-5 form-group">
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success mt-3">Agregar</button>
</form>
</div>
{% endblock %}

CRUD/Formulario/templates/CRUD/form_mascota.html
{% extends "base.html" %}

{% block title %}Formulario{% endblock %}

{% block content %}

<div class="pt-5">
<form method="post">
    {% csrf_token %}
    {{ form2.as_p }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Agregar</button>
</form>
</div>

{% endblock %}

CRUD/Formulario/templates/CRUD/index.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}
 
{% block content %}

<form method="post">
  {% csrf_token %}
  <label>Nombre de usuario</label>
  <input type='text' name="username">
  <label>Contraseña</label>
  <input type="password" name="password">
  <a href="#">Olvidé mi contraseña</a>
  <input type="submit" value="Ingresar">
</form>

{% endblock %}

CRUD/Formulario/templates/CRUD/list.html
{% extends "base.html" %}

{% block title %}Lista de personas{% endblock %}

{% block aside %}
<div class="pt-4 px-auto center">
<div class="card bg-light" style="max-width: 18rem;">
  <div class="card-header">Información</div>
  <div class="card-body">
    <h5 class="card-title">Bienvenido</h5>
    <p class="card-text">Gracias por usar nuestros servicios, agrega personas y mascotas.</p>
  </div>
</div>
</div>
{% endblock %}
 
{% block content %}

{% if object_list %}
  <h2 class="pt-4 pb-2">Lista de personas</h2>
  <table class="table table-striped table-light table-sm">

    <thead class="thead-dark">
      <tr>
        <th>Nombre</th>
        <th>Teléfono</th>
        <th>Correo</th>
        <th>Genero</th>
        <th>Fecha de nacimiento</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      {% for persona in object_list %}
      <tr>
        <td>{{ persona.nombre }}</td>
        <td>{{ persona.telefono }}</td>
        <td>{{ persona.email }}</td>
        <td>{{ persona.genero }}</td>
        <td>{{ persona.dob }}</td>
        <td><a href="{% url 'persona:editar_persona' persona.pk %}"><button type="button" class="btn btn-outline-primary">Editar</button></a></td>
        <td><a href="{% url 'persona:eliminar_persona' persona.pk %}"><button type="button" class="btn btn-outline-danger">Eliminar</button></a></td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

<a href="{% url 'persona:crear_persona' %}"> <button type="button" class="btn btn-success">Agregar</button></a>

{% else %}
<div class="pt-4">
<div class="jumbotron">
  <h1 class="display-4">Bienvenido</h1>
  <p class="lead">Este sistema de base de datos guarda mascotas con sus respectivos dueños. Estás entrando a la mejor experiencia de tu vida.</p>
  <hr class="my-4">
  <p>Parece que todavía no hay personas registradas en tu base de datos.</p>
  <p>¿Que te parece si agregamos algunas?</p>
  <a href="{% url 'persona:crear_persona' %}"> <button type="button" class="btn btn-success">Agregar</button></a>
</div>
</div>
{% endif %}

{% include "pagination.html" with page=object_list %}

{% endblock %}

CRUD/Formulario/templates/CRUD/list_mascotas.html
{% extends "base.html" %}

{% block title %}Lista de mascotas{% endblock %}
 
{% block content %}

{% if object_list %}
  <h2 class="pt-4 pb-2">Mascotas</h2>
  <table class="table table-striped table-light table-sm">

    <thead class="thead-dark">
      <tr>
        <th>Dueño</th>
        <th>Nombre</th>
        <th>Edad</th>
        <th>Especie</th>
        <th>Color</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      {% for mascota in object_list %}
      <tr>
        <td>{{ mascota.persona }}</td>
        <td>{{ mascota.nombre }}</td>
        <td>{{ mascota.edad }}</td>
        <td>{{ mascota.especie }}</td>
        <td>{{ mascota.color }}</td>
        <td><a href="{% url 'persona:editar_mascota' mascota.pk %}"><button type="button" class="btn btn-outline-primary">Editar</button></a></td>
        <td><a href="{% url 'persona:eliminar_mascota' mascota.pk %}"><button type="button" class="btn btn-outline-danger">Eliminar</button></a></td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

<a href="{% url 'persona:crear_mascota' %}"> <button type="button" class="btn btn-success">Agregar</button></a>

{% else %}
<div class="pt-4">
<div class="jumbotron">
  <h1 class="display-4">Mascotas</h1>
  <p class="lead">Aquí se mostrarán las mascotas registradas.</p>
  <hr class="my-4">
  <p>Parece que todavía no hay mascotas registradas en tu base de datos.</p>
  <p>¿Que te parece si agregamos algunas?</p>
  <a href="{% url 'persona:crear_mascota' %}"> <button type="button" class="btn btn-success">Agregar</button></a>
</div>
</div>
{% endif %}



{% include "pagination.html" with page=object_list %}

{% endblock %}